import './globals.css'
import { Assistant } from 'next/font/google'
import Layout from "@/components/Layout/Layout";

const inter = Assistant({ subsets: ['latin'] })

export const metadata = {
  title: {
      title: 's',
      template : ''
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <Layout >
        {children}
      </Layout>
      </body>
    </html>
  )
}
